---
title: "data_viz_day8"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
# attach packages
library(tidyverse)
library(here)
library(janitor)
library(patchwork)
library(ggrepel)
library(gghighlight)
library(ggExtra)
library(ggbeeswarm)
```

```{r}
lizards <- read_csv(here("data_tidy", "lizards.csv"))
```


```{r}
ggplot(lizards, aes(x = total_length, y = weight)) + geom_point(aes(x = total_length, y = weight))


ggplot(data = lizards) + 
  geom_point(aes(x = total_length, y = weight))

ggplot() + 
  geom_point(data = lizards, aes(x = total_length, y = weight))
```


```{r}
ggplot(lizards, aes(x = total_length)) + geom_histogram()
```

```{r}
ggplot(lizards, aes(y = common_name, x = weight)) + geom_jitter()
```

```{r}
ggplot(data = lizards, aes(x = weight)) + geom_histogram(fill = "slateblue4",
                                                         linewidth = 2,
                                                         linetype = "dotted")
```



```{r}
ggplot(data = lizards, aes(x = total_length, y =weight)) + 
  geom_point(color = "#3E92CC",
             fill = "#18435A",
             shape = 22, 
             size = 3,
             alpha = 0.2)
  
ggplot(lizards, aes(x = total_length, y = weight)) +
  geom_point(aes(color = common_name,
                 size = total_length),
             alpha = .5) + 
  scale_color_discrete(type = c("blue",
                                  "green",
                                  "yellow",
                                  "pink",
                                  "orange",
                                  "gold",
                                  "red"))
```


```{r}
ggplot(lizards, aes(x = site, y = weight)) + geom_jitter(aes(color =  common_name)) + 
  theme_minimal()
```


```{r}
ggplot(lizards, aes(x = total_length, y = weight)) + geom_point() +
  labs(x = "Total length (mm)",
       y = "Weight (grams)",
       title = "Lizard size")

```


```{r}
ggplot(lizards, aes(x = total_length, y = weight)) + 
  geom_point() +
  facet_wrap(~common_name, ncol = 3, scales = "free") + 
  labs(x = "Total Length (mm)",
       y = "Weight (grams)")
  
```

```{r}
ggplot(lizards, aes(x = total_length, y = weight)) +
  geom_point() +
  facet_grid(sex ~ tail)
```

```{r}
lizards_count <- lizards %>%
  count(common_name) %>%

ggplot(lizards_count, 
       aes(y = fct_reorder(common_name, n), x = n)) + 
  geom_col()

```

```{r}
ggplot(lizards, aes(x = total_length, y = weight)) + 
  geom_point(aes(colour = common_name),
             size = 2) +
  theme_minimal() + 
  labs(x = "Total length (mm)",
       y = "weight (g)",
       color = "Lizards species") + 
  facet_wrap(~common_name, scales = "free")
```

```{r}
ggplot(data = lizards, aes(y = fct_infreq(common_name))) + 
  geom_bar(aes(fill = site)) + 
  theme_minimal() + 
  labs(x = "Lizard counts",
      y = "Species (common name)") +
  facet_grid(sex ~ tail)

```

```{r}
ggplot(lizards, aes(x = total_length, y =weight)) + 
  geom_point(size = 3.5) +
  scale_x_continuous(breaks = c(0, 250, 500),
                     limits = c(0, 500)) +
  scale_y_continuous(breaks = seq(from = 0, to = 70, by = 10),
                     limits = c(0, 70)) +
  theme_light()
  
```

```{r}
lizards_count <- lizards %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  count(date)
 
ggplot(lizards_count, aes(x = date, y = n)) + 
  geom_line() + 
  # or this -- scale_x_date(breaks = scales::breaks_pretty())
  scale_x_date(breaks = scales::breaks_width("3 years"),
               labels = scales::label_date("'%y"))
  
```


```{r}
ggplot(lizards, aes(x = total_length, y = weight)) + 
  geom_point(aes(color = total_length), #weight,
                 size = 3.5) + 
  scale_color_steps2(low = "green", mid = "white", high = "red", midpoint = 150,
                     breaks = c(50, 75, 150, 200, 250, 280))
  #scale_color_steps(low = "red", high = "black")
  #scale_color_gradientn(colors = c("orange", "red", "purple", "navy", "black"))
  # scale_color_gradient(low = "red", high = "blue")
```


```{r}
p <- ggplot(lizards, aes(x = total_length, y = weight)) + 
  geom_point()

p +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major =element_line(color = "red"),
        plot.background = element_rect(fill = "pink"),
        text = element_text(size = 12, family = "serif"),
        axis.text.x = element_text(color = "blue"),
        axis.text.y = element_text("green"),
        panel.background = element_rect(color = "purple", fill = "yellow"))
```


```{r}
p +
  geom_hline(yintercept = 40, color = "blue", linetype = "dashed") +
  geom_vline(xintercept = 100, color = "red") +
  # annotate("text", x = 100, y = 50, label = "COOL!", color = "purple")
  annotate("text", x = 350, y = mean(lizards$weight) + 2, label = "Mean weight")
```

```{r}
mono <- read_csv(here("data_tidy", "mono.csv"))

ggplot(mono, aes(x = year, y = lake_level)) + 
  geom_rect(aes(xmin = 1941,
                xmax = 1983, 
                ymin = 6350,
                ymax = 6440),
            fill = "gray90") +
  geom_line() + 
  labs(x = "Year",
       y = "Lake surface level\n(feet above sea level)\n",
       title = "Mono Lake (1850 ~ 2017)",
       caption = "Data: Mono Basin Clearinghouse") +
  scale_y_continuous( limits = c(6350, 6440),
                      breaks = c(6370, 6400, 6430),
                      labels = scales::label_comma()) +
  scale_x_continuous(limits = c(1850, 2020),
                     breaks = seq(1850, 2010, by = 20),
                     expand = c(0,0)) +
  geom_hline(yintercept = 6350, linetype = "dashed") +
  annotate("text", x = 1910, y = 6370, 
           label = "Decreased shrimp abundance expected\n(6,360 feet above sea level") +
    annotate("text", x = 1962, y = 6425,
             label = "Unrestricted diversions\n(1941 ~ 1983", 
             size = 3) +
    theme_minimal()
  

```

